"""Create the initial deduplicated register. Do not rerun after status updates."""
from pathlib import Path
import json
root=Path(__file__).resolve().parent
# id, severity, category/role, system, observation/cause, correction, verification, evidence status
rows=[
('AUTH-01','CRITICAL','Security / candidate','workers-api/src/index.ts; ApplicationSuccess.tsx','Public password registration trusts application ID/email; the public form can create that pair for any email. Existing hashes can be overwritten.','Require verified candidate session; derive ownership from session; move password setting into portal.','Anonymous and cross-email attempts leave account unchanged; verified owner can set/reset.','VERIFIED'),
('AUTH-02','HIGH','Authentication / candidate','workers-api/src/index.ts; services/auth.ts','Password route signs an already signed session and sets the wrong cookie; portal rejects it.','Issue the existing signed session once, with the shared cookie name.','Password and magic-link tokens work with Bearer and cookie, and wrong/expired tokens fail.','VERIFIED'),
('AUTH-03','HIGH','Authentication / candidate','CandidateApplications.tsx; workers-api/src/index.ts','UI logout clears localStorage without server revocation; cookie/token remains usable.','Revoke before declaring sign-out successful; handle revocation failure.','Old token and cookie rejected after UI/API logout.','INFERENCE'),
('API-01','HIGH','API / all roles','workers-api/src/index.ts parseJson','JSON helper recursively calls itself; valid contact JSON returns Required/400 and shared mutations fail.','Parse the request once; return null for malformed/non-object bodies.','Valid contact/admin/assessment JSON accepted; malformed, null and arrays rejected with 400.','VERIFIED'),
('DATA-01','HIGH','Data / candidate','workers-api/src/index.ts; schema.ts; services/applications.ts','Application submission accepts nonexistent/closed job titles and no CV; fields lack trim/length rules and campaign slug is stripped.','Authoritative active-job binding, bounded normalized input, required CV, attribution.','Valid apply works; unknown/closed jobs, whitespace and invalid files rejected without writes.','VERIFIED'),
('DATA-02','HIGH','Data / candidate','workers-api/src/schema.ts; repositories.ts; JobPage.tsx','No duplicate submission constraint or idempotency; client can resubmit after network uncertainty.','Define submission identity and safe replay using persisted constraint/idempotency.','Parallel/replayed submit produces one application and one logical notification set.','INFERENCE'),
('FILE-01','HIGH','Storage / candidate/admin','workers-api/src/services/storage.ts; services/applications.ts; index.ts','MIME-only CV checks, unsanitized names, pre-validation buffering, orphan upload on insert failure, deletion error swallowed.','Validate size/type/name/content; safe attachment headers; compensate failed insert and retain retryable deletion.','Wrong MIME/signature/oversize/empty rejected; storage/SQL failure recovery and ownership enforced.','INFERENCE'),
('AUTH-04','HIGH','Privacy / candidate','workers-api/src/index.ts candidate application responses','Raw application spread includes room/meeting fields before shortlist despite blank nextStep.','Explicitly redact unpublished private fields according to server status.','New/rejected candidate JSON contains no private room/key; shortlisted owner sees intended data.','INFERENCE'),
('ASSESS-01','HIGH','Workflow / candidate','AssessmentPage.tsx','Null payload loading branch precedes error branch; completed result branch follows no-assessment branch.','Render errors and recorded completion first; add actionable recovery.','Missing/invalid/expired link shows error; completed assessment shows saved result on reload.','VERIFIED'),
('ASSESS-02','HIGH','Trust / candidate','PreChecks.tsx; workers-api/src/services/techcheck.ts','Instant validation declares success after delay without server report; installer bypasses downloaded-file safeguards.','Require actual evidence for verified claims; remove safeguard bypass and misleading success.','No verified status without report; no automatic unsafe installation; honest optional path.','INFERENCE'),
('ASSESS-03','HIGH','Workflow / candidate','AssessmentPage.tsx; PreChecks.tsx; workers-api/src/index.ts','Optional/no-pass-mark copy conflicts with speed/typing gates; track can depend on supplied job slug.','Use authoritative job track and consistent optional prechecks with bounded network probes.','Track substitution rejected; slow/mobile candidates can follow documented optional flow.','INFERENCE'),
('PRIV-01','HIGH','Privacy / candidate/referral','NextStepFlow.tsx; workers-api/src/index.ts','Background room flow silently loads third-party sites through multiple mechanisms and unbounded backend redirect fetch.','Remove silent background fetch; present explicit external action with validated URL.','No external request before user action; private/unsafe schemes rejected; room action works.','INFERENCE'),
('DEVICE-01','MEDIUM','Access / candidate/referral','lib/deviceGuard.ts; ReferralPage.tsx','Touch/coarse-pointer heuristics can block touch laptops and are presented as authoritative identity.','Use device hints for guidance; avoid unsupported definitive device claims.','Touch laptop/mobile behavior matches feature capabilities and provides usable next action.','INFERENCE'),
('MAIL-01','HIGH','Email / candidate/admin','workers-api/src/services/email.ts; services/applications.ts','Successful void email result is logged as failed; retries lack idempotency/classification/durable visibility.','Explicit send outcome; stable event identity; bounded transient retries; observable failures.','Successful HR send not logged as failed; uncertain retry does not duplicate; permanent failures visible.','VERIFIED'),
('MAIL-02','HIGH','Email / all recipients','workers-api/src/services/email.ts','No plain text part; real receipt, DNS authentication, sender/reply-to delivery not established.','Add text parity and verify designated real recipient/provider evidence.','All real product email events reach test inbox; links/text/reply-to/headers checked.','PARTIALLY VERIFIED'),
('COPY-01','HIGH','Trust / public','ClientMarquee.tsx; LandingPage.tsx; CareersPage.tsx; Legal.tsx','Placeholder client endorsements and unsupported country/service guarantees conflict with implemented behavior.','Remove unverified endorsements; use factual neutral copy and consistent process/privacy language.','No fabricated proof; legal/product/assessment/email claims match observable behavior.','INFERENCE'),
('NAV-01','MEDIUM','Navigation / public','site navigation and footer','Homepage Candidate access opens careers; footer LinkedIn is generic; mobile menu lacks sign-in.','Point sign-in to login; remove generic social link until verified; expose mobile sign-in.','Desktop/mobile candidate navigation reaches login and all footer links are meaningful.','VERIFIED'),
('A11Y-01','MEDIUM','Accessibility / all roles','JobPage.tsx; CareersPage.tsx; admin forms','Six application selects, four filters and other fields lack associated labels; errors are inconsistently announced.','Programmatic labels, descriptions, invalid state and error focus; audit shared form primitives.','Named controls, keyboard traversal and error recovery at all widths.','VERIFIED'),
('COPY-02','LOW','Copy / public','CareersPage.tsx / date formatting','Job card renders 1 months ago.','Use singular/plural date formatting with date validation.','One month/day/year uses singular; invalid date has safe fallback.','VERIFIED'),
('SEO-01','MEDIUM','SEO / public','index.html; Pages Functions; SiteLayout','sitemap.xml returns HTML; metadata conflicts with positioning; protected indexing policy unverified.','Real sitemap, consistent canonical/meta, valid job data, noindex private/auth paths.','XML validates; metadata/canonical/schema reflect actual pages; private paths noindex.','VERIFIED'),
('PERF-01','MEDIUM','Performance / public','App.tsx; frontend build','All routes including admin/xlsx eagerly imported; main JS 1164.82 kB.','Split route-heavy code while preserving navigation and error fallback.','Build and navigation pass; visitor payload reduced; measure runtime performance.','VERIFIED'),
('OPS-01','HIGH','Deployment / operator','pnpm-workspace.yaml; .github/workflows/ci-cd.yml','Frozen install fails allowBuilds; CI assumes pnpm auto-install, suppresses secret errors and deploys components independently.','Deterministic package setup; required tests/build gates; explicit successful release prerequisites.','Clean install/checks/build pass; workflow validated; failure prevents publish.','PARTIALLY VERIFIED'),
('OPS-02','MEDIUM','Data operations / operator','workers-api/migrate.mjs; runtime schema helpers','Migration errors can continue; repeated request-time DDL and cached rejected schema promises complicate recovery.','Versioned fail-fast migrations and retryable initialization; avoid implicit data repair during reads.','Fresh/upgrade/replay/failure migrations behave predictably and preserve data.','INFERENCE'),
('SEC-01','MEDIUM','Security / all roles','workers-api/src/index.ts; services/auth.ts; config.ts','JWT claims/cookie parsing need strict validation; security/cache headers absent; env/client state globally mutable.','Validate claims/algorithms and malformed cookies; request-safe bindings; appropriate headers.','Malformed/forged/role-swapped/expired auth fails; private responses no-store; isolation tested.','PARTIALLY VERIFIED'),
('PRIV-02','MEDIUM','Privacy / operator','Legal.tsx; techcheck.ts; activities','Retention/all-actions-logged/no-install/privacy statements exceed verified implementation.','Align disclosures and implement or remove unsupported operational promises.','Inventory matches disclosure; selected sensitive admin changes logged; retention policy actionable.','INFERENCE'),
('LEGACY-01','MEDIUM','Maintenance / operator','repository-inventory.json; history-secrets.json','45 legacy mentions,38 domain dependencies and credential-shaped historical URLs need classification.','Classify safely; remove active stale references and literal credentials; document migration dependencies.','No active unwanted legacy branding or exposed real secrets; migration checklist complete.','PARTIALLY VERIFIED'),
]
findings=[]
for id,severity,category,source,observed,fix,verify,status in rows:
 findings.append(dict(id=id,severity=severity,status='OPEN',category_role=category,source=source,observed=observed,expected=fix,root_cause='See 24_ROOT_CAUSES.md; boundary/state/contract inconsistency described in observed behavior.',impact='Affected role cannot rely on the expected behavior; severity reflects security, workflow or trust impact.',recommended_correction=fix,verification_requirement=verify,evidence='05_BASELINE_REVIEW.md; 14_EMAIL_SYSTEM.md; evidence/workflow-baseline.json and associated source/DOM/provider evidence.',baseline_verification=status,final_verification='NOT VERIFIED'))
(root/'evidence/master-findings.json').write_text(json.dumps(findings,indent=2),encoding='utf8')
parts=['# Master findings\n\nInitial baseline register. All findings remain open until their verification requirements are met. Source-only conclusions are distinguished from executed tests.\n']
for f in findings:
 parts.append('\n## '+f['id']+' — '+f['severity']+'\n')
 for k,v in f.items():
  if k not in ['id','severity']:parts.append('\n- **'+k.replace('_',' ')+':** '+v)
 parts.append('\n')
(root/'23_MASTER_FINDINGS.md').write_text('\n'.join(parts),encoding='utf8')
print(f'{len(findings)} deduplicated findings recorded')
