/** First required application prompt for each currently published fallback role. */
export const ROLE_SPECIFIC_QUESTION_PROMPTS: Readonly<Record<string, string>> = {
  actuary: "Describe actuarial work you have delivered, such as pricing, reserving, forecasting, or capital analysis, and how you validated its assumptions.",
  "ai-data-annotator-labeler": "How do you apply a labeling rubric to ambiguous AI or data examples and document cases that do not fit the rules?",
  "back-end-developer": "Describe a backend API or service you built or maintained and one decision you made to protect reliability or data integrity.",
  "business-analyst": "Give an example of a business need you translated into verifiable requirements, acceptance criteria, or a process change.",
  "captioner-subtitler": "How do you keep captions synchronized, accurate, and readable when audio is unclear or speakers overlap?",
  "chat-support-representative": "Describe how you prioritized several simultaneous support chats while keeping each case accurate and its next action clear.",
  "ceo-fractional": "What organization-level outcome have you owned in a fractional or advisory capacity, and how did you align leaders on priorities?",
  "cto-fractional": "Describe a technical roadmap or architecture decision you led and how you balanced delivery, reliability, security, and cost.",
  "clinical-research-associate": "Describe how you keep study visits, source records, protocol deviations, and follow-ups complete and traceable.",
  "cloud-architect": "Describe a cloud architecture you designed or reviewed and how you assessed availability, security, migration, and operating cost.",
  "corporate-counsel": "Describe a contract or legal matter you handled and how you identified jurisdiction-specific risks and explained practical options.",
  "data-entry-clerk": "What checks do you use when entering high-volume records to catch omissions, mismatches, and duplicate entries?",
  "data-verification-specialist": "How do you verify a record against an authoritative source and document any discrepancy or unresolved ambiguity?",
  "director-of-engineering": "Describe an engineering delivery system or organization you improved, the outcome, and how you measured the change.",
  "director-of-remote-operations": "Describe a remote operating process you led and how you clarified ownership, service expectations, and escalations across teams.",
  "dropshipping-store-manager": "How have you coordinated product listings, supplier updates, order exceptions, and fulfilment performance in an online store?",
  "ecommerce-store-assistant": "Which online-store tasks have you handled across catalogues, orders, product information, or customer hand-offs, and how did you check accuracy?",
  "email-support-specialist": "How do you investigate a customer issue across email threads and account records while giving clear, accurate next steps?",
  "financial-analyst": "Describe an analysis or forecast you prepared, the assumptions you documented, and how you checked actual results against estimates.",
  "front-end-web-developer": "Describe a web interface you implemented and how you verified responsive behavior, accessibility, and cross-browser support.",
  "general-audio-transcriber": "How do you mark uncertain speech, speaker changes, and terminology while preserving the meaning of the recording?",
  "general-virtual-assistant": "Describe a recurring administrative workflow you managed from request to completion and how you prevented missed follow-ups.",
  "grant-writer": "Describe a grant proposal you contributed to and how you tracked funder requirements, evidence, and submission deadlines.",
  "head-of-growth": "Describe a growth experiment or channel strategy you led and what evidence determined whether to scale, change, or stop it.",
  "inbound-customer-service-rep": "Describe an inbound customer request you could not resolve immediately and how you kept the customer informed through resolution.",
  "instructional-designer": "Describe a learning module you designed and how its objectives, practice activities, and assessment fit together.",
  "lead-generation-assistant": "How do you qualify a prospect against defined criteria and keep CRM records and follow-ups accurate and respectful?",
  "ml-ai-engineer": "Describe an ML or AI feature you built or evaluated, including how you measured quality and handled uncertainty or failure cases.",
  "medical-coding-specialist": "Which coding systems or workflows have you used, and how do you verify code selection against documentation and applicable standards?",
  "online-content-moderator": "Describe a moderation decision involving ambiguous content and how you applied policy, context, and escalation rules.",
  "online-k12-tutor": "How do you adapt an explanation or practice activity when a K–12 learner is stuck on a particular concept?",
  "operations-analyst": "Describe an operational dataset or workflow you analyzed and how the findings informed a measurable process or decision.",
  "outbound-telemarketer": "How do you conduct respectful outbound calls, qualify a contact, record the outcome, and stop follow-up when requested?",
  "paid-ads-ppc-specialist": "Describe a paid-search or social campaign you optimized, the metrics you used, and how you controlled spend while testing changes.",
  "penetration-tester": "Describe an authorized security assessment you performed, how you maintained scope, and how you reported findings safely.",
  "staff-software-engineer": "Describe a cross-team technical decision you led and how you improved architecture while helping other engineers grow.",
  "product-manager": "Describe a product decision you made using customer or usage evidence, what you prioritized, and how you measured the result.",
  proofreader: "Which checks help you catch grammar, terminology, formatting, and factual inconsistencies without changing the author's intended meaning?",
  "qa-software-tester": "Describe a test strategy you used for a software feature, including case selection, defect reporting, and fix verification.",
  "quant-analyst": "Describe a quantitative model or analysis you built, how you validated its assumptions, and what limitations you communicated.",
  "telehealth-physician": "Which jurisdictions are you licensed to practise in, and how do you handle telehealth documentation, privacy, and clinical escalation?",
  teleradiologist: "Which imaging areas and jurisdictions are within your current credentials, and how do you maintain report accuracy and turnaround?",
  "salesforce-administrator": "Describe a Salesforce configuration or automation you delivered, including permissions, testing, and handover documentation.",
  "scrum-master-agile-coach": "Describe how you helped a delivery team resolve blockers or improve flow, and what changed as a measurable result.",
  "search-engine-ai-evaluator": "How do you apply evaluation guidelines to borderline search or AI responses and support a rating with specific evidence?",
  "senior-fullstack-engineer": "Describe a production feature you delivered across frontend and backend and a trade-off you made for reliability or maintainability.",
  "seo-director-manager": "Describe an organic-search strategy you led and how you separated durable gains from seasonal or algorithm changes.",
  "solutions-architect": "Describe how you translated business constraints into a solution design and documented trade-offs, risks, and rollout steps.",
  "survey-micro-task-specialist": "How do you answer repetitive survey or classification tasks consistently and flag unclear or ineligible cases?",
  "systems-administrator": "Describe a systems incident or access change you handled, how you diagnosed it, and how you documented recovery safely.",
  "technical-writer": "Describe a technical guide you produced and how you verified its steps with a user, operator, or subject-matter expert.",
  "virtual-receptionist": "How do you route calls and messages accurately while protecting confidential information and escalating urgent exceptions?",
  "backend-developer": "Describe a backend feature you delivered and how you handled API contracts, validation, and failure behavior.",
  "billing-specialist": "Describe how you resolve a billing discrepancy by checking source records, calculations, approvals, and communication history.",
  "community-manager": "Describe how you grew or supported an online community while handling moderation and difficult member interactions.",
  "content-writer": "Share a writing sample for a relevant audience and explain how you researched, structured, and checked it before delivery.",
  "cybersecurity-analyst": "Describe how you triaged a security alert, validated its significance, and documented or escalated the finding.",
  "data-analyst": "Describe an analysis or dashboard you built, how you checked the underlying data, and what decision it supported.",
  "data-annotation-specialist": "Describe how you maintained consistent labels across a large task set and handled uncertain or conflicting examples.",
  "data-engineer": "Describe a data pipeline you built or maintained and how you checked schema changes, data quality, and failed runs.",
  "database-administrator": "Describe a database maintenance or recovery task you handled and how you verified access, integrity, and performance afterward.",
  "devops-engineer": "Describe a delivery or infrastructure improvement you made and how you measured deployment reliability or recovery time.",
  "email-marketing-specialist": "Describe an email campaign you prepared and how you handled segmentation, consent, measurement, and delivery issues.",
  "frontend-developer": "Describe a frontend feature you implemented and how you verified interaction states, responsive behavior, and accessibility.",
  "full-stack-developer": "Describe a feature you built across client and server code and how you kept its data flow and error states consistent.",
  "graphic-designer": "Share a visual-design sample relevant to the role and explain how you moved from brief and feedback to final files.",
  "hr-assistant": "Describe how you handled a confidential HR record or coordination task while maintaining accuracy and appropriate access.",
  "inventory-management-assistant": "Describe how you tracked stock movement or a count discrepancy and kept the inventory record aligned with source evidence.",
  "it-support-specialist": "Describe a user-support issue you diagnosed and how you communicated the fix or escalation in plain language.",
  "junior-software-developer": "Share a software project you contributed to and explain one implementation choice, test, or review that improved it.",
  "machine-learning-engineer": "Describe how you prepared, evaluated, or operated an ML model and how you checked performance on relevant cases.",
  "mobile-app-developer": "Describe a mobile feature you built and how you tested device behavior, network failure, and release readiness.",
  "order-processing-specialist": "Describe how you processed an order with missing or conflicting details and kept its status and customer hand-off accurate.",
  "payroll-specialist": "Describe the checks you perform before finalizing a payroll run and how you resolve a discrepancy securely.",
  "qa-engineer": "Describe a release-risk area you tested and how you decided what to automate, test manually, or block from release.",
  "recruiting-coordinator": "Describe how you coordinated a multi-person interview schedule and kept candidate records and updates consistent.",
  "research-assistant": "Describe a research task you supported and how you maintained source traceability, protocol consistency, and data quality.",
  "seo-specialist": "Describe an SEO issue or opportunity you investigated and how you validated the change using search and site evidence.",
  transcriptionist: "How do you deliver an accurate transcript when audio quality, speaker attribution, or specialist vocabulary is uncertain?",
  "ui-ux-designer": "Describe a user flow you researched or redesigned and how you used feedback or usability evidence to refine it.",
  "video-editor": "Share a video edit you completed and explain how you shaped pacing, audio, revisions, and export specifications.",
  "virtual-assistant": "Describe how you managed competing calendar, inbox, or administrative requests and kept owners aware of outstanding actions.",
  "executive-assistant": "Describe how you protected an executive's time across competing priorities while handling confidential information reliably.",
  "customer-support-specialist": "Describe a customer issue you owned through resolution and how you documented context and follow-up for the team.",
  "customer-success-representative": "Describe how you helped a customer reach an agreed outcome and recognized when an issue needed escalation.",
  "administrative-coordinator": "Describe an administrative process you coordinated across people or deadlines and how you kept records current.",
  "real-estate-operations-associate": "Describe how you coordinate document-heavy property or transaction work and catch missing items before hand-off.",
  "lead-generation-specialist": "Describe how you identify and qualify suitable prospects while keeping outreach relevant and CRM data reliable.",
  "appointment-setter": "How do you confirm a prospect's fit and availability, set expectations for a meeting, and record the outcome accurately?",
  "data-entry-specialist": "Describe the validation steps you use to enter or update records accurately when source information is incomplete.",
  "project-coordinator": "Describe how you tracked project actions, owners, dependencies, and risks to keep a cross-functional delivery on schedule.",
  "social-media-assistant": "Describe how you prepared or scheduled social content and checked links, copy, assets, and approvals before publishing.",
  "marketing-assistant": "Describe a marketing task you coordinated and how you kept its assets, approvals, deadlines, and outcome records organized.",
  bookkeeper: "Describe a bookkeeping reconciliation you completed and how you handled an unmatched transaction or supporting document.",
  "technical-support-representative": "Describe a technical issue you diagnosed with a user and how you verified the resolution before closing the case.",
};
